# Generated by Django 3.2.3 on 2021-05-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_user_position_usermodel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='position',
            field=models.CharField(choices=[('전문가', '전문가'), ('일반', '일반')], help_text='전문가인지 일반유저인지 선택해주세요!', max_length=10),
        ),
    ]
