# Generated by Django 3.2.3 on 2021-06-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me_app', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='idea',
        ),
    ]
